import type { Metadata } from "next";
import { Spline_Sans } from "next/font/google";
import "./globals.css";
import PageTransition from "./components/PageTransitionWrapper/PageTransition";
import SmoothScroll from "../app/components/SmoothScroll/SmoothScroll";
import EmailProvider from "../app/Provider/EmailProvider";
import Footer from '../app/components/Footer/Footer'
import Nav from "../app/components/Nav";
const splineSans = Spline_Sans({
  variable: "--font-spline-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "UXMIR Portfolio",
  description: "Generated by UXMIR Portfolio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${splineSans.className} antialiased`}>
        <PageTransition>
          <SmoothScroll>
            <EmailProvider>
              <Nav />
              {children}
              <Footer/>
            </EmailProvider>
          </SmoothScroll>
        </PageTransition>
      </body>
    </html>
  );
}
