import type { Metadata } from "next";
import { Spline_Sans } from "next/font/google";
import "./globals.css";
import PageTransition from "./components/PageTransitionWrapper/PageTransition";
import Nav from '../app/components/Nav'
const splineSans = Spline_Sans({
  variable: "--font-spline-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${splineSans.className} antialiased`}
      >
        {/* <PageTransition> */}
        <Nav/>
        {children}
        {/* </PageTransition> */}
      </body>
    </html>
  );
}